- name: Cross ping all the nodes to establish node-to-node IPSec tunnels
  shell: "ping -c2 {{ default_interface }}"
  with_items: "{{groups['masters']}}"
  failed_when: false
  tags: ipsec

- name: Check IPSec tunnels
  shell: "ipsec whack --trafficstatus"
  register: check_ipsec_result
  tags: ipsec

- name: Display IPSec tunnels
  debug:
    var=check_ipsec_result.stdout
  tags: ipsec
